### ISSUE TITLE
Windows Phone 8.1 Support

### ISSUE THREAD

**Issue by joshboon** [brianhama/tinder#2]
I tried to get this monster to run on windows phone 8.1 and seem to have issues with profile saves and potentially matches though I may just not be pretty enough ;)  I cracked it open in visual studio but it looks to have dependencies on Telerik which from my googling reveals that it's something I'd need to purchase to get it to build.  I'm happy to help test if you're considering releasing an update.

**Comment by aplocher** [comment]
Shoot it may be too late but I read that at the beginning of last week they were giving out free dev licenses for the telerik control suites for W8 and WP8. It's likely over but maybe check it out. Anyone who does any .net development/consulting should have telerik, it's a must-have imo

**Comment by bviktor** [comment]
Yup, for me it always says:

_You will need to update your Facebook profile in order to change some aspects of your profile._

And then it loads my earlier profile made with the now-pulled 6tindr and there's no way to change pictures. Also crashes randomly.

**Comment by EricSchrader** [comment]
I was able to install Telerik, right click on the TInderApp project and go to Telerik windows phone and convert it. I am able to debug, but my FB wont sign in. Seems to be taking forever to authenticate. InitialPage.xaml.cs                     await Authenticate(accessToken, user.Id);

**Comment by bviktor** [comment]
Just a FYI, now there's a lot of alternatives in the store: Timber, 6tin, and a 3rd one I can't remember.

**Comment by brianhama** [comment]
I have fixed the authentication issue in the latest code.
