### ISSUE TITLE
Hi are you planing to update this api? i would like to create a client in xamarin

### ISSUE THREAD

**Issue by egarim** [brianhama/tinder#6]
Hi are you planing to update this api? i would like to create a client in xamarin

**Comment by brianhama** [comment]
I don't currently have any plans on updating it, but you are welcome to fork it or contribute to this project.

**Comment by egarim** [comment]
Do you have any documentation or can we meet over Skype so your can give me a little Guide 

Sent from Outlook

On Sun, Oct 11, 2015 at 12:19 AM -0700, "Brian P. Hamachek" notifications@github.com wrote:

I don't currently have any plans on updating it, but you are welcome to fork it or contribute to this project.
